use rand::{thread_rng, Rng};

const WORD_LIST: &[&str] = &[
    "ability", "abroad", "abuse", "access", "accident", "account", "action", "active", "activity", "actor",
    "address", "admin", "admit", "adult", "advance", "advice", "affair", "affect", "afford", "afraid",
    "agency", "agent", "agree", "ahead", "alarm", "album", "alcohol", "alert", "alien", "alive",
    "allow", "almost", "alone", "along", "already", "also", "alter", "always", "amazing", "among",
    "amount", "analysis", "analyst", "analyze", "ancient", "anger", "angle", "angry", "animal", "annual",
    "another", "answer", "anxiety", "anybody", "anyone", "anyway", "anywhere", "appeal", "appear", "apple",
    "apply", "approach", "area", "argue", "argument", "arise", "around", "arrive", "article", "artist",
    "assume", "attack", "attempt", "attend", "attitude", "attract", "audience", "author", "average", "avoid",
    "award", "aware", "badly", "balance", "banana", "basic", "battle", "beach", "beauty", "become",
    "bedroom", "before", "begin", "behalf", "behave", "behind", "being", "belief", "believe", "belong",
    "benefit", "beside", "better", "between", "beyond", "bicycle", "bigger", "biology", "birthday", "black",
    "blame", "blanket", "block", "blood", "board", "boost", "border", "bottle", "bottom", "brain",
    "branch", "bread", "break", "breast", "breath", "bridge", "brief", "bright", "bring", "broad",
    "broken", "brother", "brown", "brush", "budget", "build", "bullet", "bunch", "burden", "bureau",
    "button", "buyer", "camera", "campus", "cancel", "cancer", "candle", "canvas", "capacity", "capital",
    "capture", "carbon", "career", "carpet", "carry", "castle", "casual", "catch", "cause", "ceiling",
    "center", "central", "centre", "century", "chain", "chair", "chance", "change", "channel", "chapter",
    "charge", "charity", "chart", "chase", "cheap", "check", "cheese", "chest", "chicken", "child",
    "choice", "choose", "church", "circle", "citizen", "civil", "claim", "class", "classic", "clean",
    "clear", "client", "climate", "climb", "clock", "close", "clothes", "cloud", "coach", "coast",
    "coffee", "cold", "collect", "college", "color", "column", "combat", "come", "comedy", "comfort",
    "comic", "command", "comment", "common", "company", "compare", "compete", "complex", "concept", "concern",
    "concert", "conduct", "confirm", "conflict", "connect", "consider", "consist", "constant", "contact", "contain",
    "content", "contest", "context", "continue", "contract", "control", "convert", "cookie", "copy", "corner",
    "correct", "cotton", "could", "council", "count", "country", "county", "couple", "courage", "course",
    "court", "cover", "craft", "crash", "crazy", "cream", "create", "credit", "crime", "crisis",
    "critic", "cross", "crowd", "crown", "crucial", "cruise", "crystal", "culture", "curious", "current",
    "curve", "custom", "cycle", "damage", "dance", "danger", "dark", "data", "daughter", "dawn",
    "deadly", "dealer", "death", "debate", "debris", "debt", "decade", "decide", "deep", "defeat",
    "defend", "define", "degree", "delay", "deliver", "demand", "dense", "deny", "depend", "depth",
    "deputy", "derive", "describe", "desert", "design", "desire", "desk", "despite", "destroy", "detail",
    "detect", "device", "dialogue", "diamond", "diary", "die", "diet", "differ", "digital", "dinner",
    "direct", "dirt", "disable", "disagree", "discover", "discuss", "disease", "dish", "dismiss", "disorder",
    "display", "distance", "district", "divide", "doctor", "document", "domestic", "door", "double", "doubt",
    "down", "downtown", "dozen", "draft", "drama", "dramatic", "draw", "drawing", "dream", "dress",
    "drink", "drive", "drop", "drug", "dry", "due", "during", "dust", "duty", "each",
    "early", "earth", "ease", "east", "easy", "eat", "economic", "economy", "edge", "edit",
    "educate", "effect", "effort", "eight", "either", "elderly", "elect", "element", "eliminate", "else",
    "emerge", "emotion", "employ", "empty", "enable", "end", "enemy", "energy", "engage", "engine",
    "enhance", "enjoy", "enormous", "enough", "ensure", "enter", "entire", "entry", "equal", "error",
    "escape", "especially", "establish", "estate", "estimate", "ethnic", "evening", "event", "ever", "every",
    "evidence", "exact", "examine", "example", "exceed", "excellent", "except", "exchange", "excited", "exclude",
    "excuse", "execute", "exercise", "exist", "exit", "expand", "expect", "expense", "expert", "explain",
    "explore", "export", "expose", "express", "extend", "external", "extra", "extreme", "face", "fact",
    "factor", "factory", "faculty", "fail", "failure", "fair", "faith", "fall", "false", "familiar",
    "family", "famous", "fantasy", "farm", "fashion", "fast", "father", "fault", "favorite", "fear",
    "feature", "federal", "fee", "feed", "feel", "feeling", "fellow", "female", "fence", "festival",
    "few", "field", "fifteen", "fifth", "fifty", "fight", "figure", "file", "fill", "film",
    "final", "finance", "find", "finding", "fine", "finger", "finish", "fire", "firm", "first",
    "fish", "fit", "fitness", "five", "fix", "flag", "flame", "flat", "flavor", "flesh",
    "flight", "float", "floor", "flow", "flower", "fluid", "fly", "focus", "folk", "follow",
    "food", "foot", "football", "force", "foreign", "forest", "forever", "forget", "form", "formal",
    "format", "former", "formula", "forth", "fortune", "forum", "forward", "found", "foundation", "four",
    "frame", "free", "freedom", "freeze", "french", "frequency", "fresh", "friend", "from", "front",
    "fruit", "fuel", "full", "fun", "function", "fund", "funny", "future", "gain", "galaxy",
    "game", "gang", "gap", "garage", "garden", "garlic", "gas", "gate", "gather", "gear",
    "gender", "general", "generate", "generation", "gentle", "get", "gift", "girl", "give", "glad",
    "glass", "global", "glove", "goal", "gold", "golf", "good", "government", "grab", "grade",
    "grain", "grand", "grant", "grass", "grave", "gray", "great", "green", "grocery", "ground",
    "group", "grow", "growth", "guard", "guess", "guest", "guide", "guilty", "guitar", "gun",
    "guy", "habit", "hair", "half", "hall", "hand", "handle", "hang", "happen", "happy",
    "hard", "harm", "hat", "hate", "have", "head", "health", "hear", "heart", "heat",
    "heavy", "heel", "height", "hell", "help", "here", "hero", "herself", "hide", "high",
    "hill", "hint", "hip", "hire", "his", "history", "hit", "hold", "hole", "holiday",
    "holy", "home", "honest", "honey", "honor", "hope", "horizon", "horror", "horse", "hospital",
    "host", "hot", "hotel", "hour", "house", "how", "however", "huge", "human", "humor",
    "hundred", "hung", "hunt", "hurt", "husband", "ice", "idea", "ideal", "identify", "if",
    "ignore", "ill", "illegal", "illness", "image", "imagine", "impact", "implement", "imply", "import",
    "impose", "improve", "include", "income", "increase", "indeed", "index", "indicate", "industry", "infant",
    "infect", "infer", "infinite", "inform", "initial", "injury", "inner", "innocent", "input", "inquiry",
    "insect", "inside", "insight", "inspect", "inspire", "install", "instance", "instead", "institute", "instruct",
    "instrument", "insurance", "intend", "intense", "intent", "interact", "interest", "internal", "internet", "interpret",
    "interval", "interview", "into", "introduce", "invest", "invite", "involve", "iron", "island", "isolate",
    "issue", "item", "itself", "jacket", "jail", "january", "jazz", "jealous", "jeans", "jewel",
    "job", "join", "joint", "joke", "journal", "journey", "joy", "judge", "judgment", "juice",
    "jump", "jungle", "junior", "jury", "just", "justice", "justify", "keep", "key", "keyboard",
    "kick", "kid", "kill", "kind", "king", "kiss", "kitchen", "knee", "knife", "knock",
    "know", "knowledge", "label", "labor", "lack", "ladder", "lady", "lake", "land", "language",
    "large", "last", "late", "later", "laugh", "launch", "law", "lawn", "lawyer", "lay",
    "layer", "lazy", "lead", "leader", "leaf", "league", "lean", "learn", "least", "leather",
    "leave", "left", "leg", "legal", "legend", "lesson", "let", "letter", "level", "library",
    "license", "lie", "life", "lift", "light", "like", "limit", "line", "link", "lion",
    "lip", "list", "listen", "little", "live", "living", "load", "loan", "lobby", "local",
    "lock", "logic", "lonely", "long", "look", "loop", "loose", "lord", "lose", "loss",
    "lost", "lot", "loud", "love", "lovely", "lover", "low", "lower", "luck", "lucky",
    "lunch", "lung", "luxury", "machine", "mad", "magazine", "magic", "magnet", "maid", "mail",
    "main", "major", "make", "male", "mall", "man", "manage", "manner", "many", "map",
    "march", "margin", "mark", "market", "marriage", "married", "marry", "mask", "mass", "master",
    "match", "material", "math", "matter", "maximum", "may", "maybe", "mayor", "meal", "mean",
    "meaning", "measure", "meat", "media", "medical", "medicine", "medium", "meet", "meeting", "member",
    "memory", "mental", "mention", "menu", "mess", "message", "metal", "method", "middle", "might",
    "military", "milk", "million", "mind", "mine", "mineral", "minimum", "mining", "minor", "minute",
    "miracle", "mirror", "miss", "missile", "mission", "mistake", "mix", "mixture", "mobile", "mode",
    "model", "moderate", "modern", "modest", "modify", "mom", "moment", "money", "monitor", "month",
    "mood", "moon", "moral", "more", "morning", "mortgage", "most", "mother", "motor", "mount",
    "mountain", "mouse", "mouth", "move", "movie", "much", "multiple", "muscle", "museum", "music",
    "musical", "musician", "must", "mutual", "myself", "mystery", "nail", "name", "narrow", "nation",
    "national", "native", "natural", "nature", "navy", "near", "nearby", "neat", "neck", "need",
    "negative", "neighbor", "neither", "nerve", "nest", "net", "network", "neutral", "never", "new",
    "news", "next", "nice", "night", "nine", "nobody", "nod", "noise", "none", "noon",
    "normal", "north", "northern", "nose", "not", "note", "nothing", "notice", "notion", "novel",
    "now", "nuclear", "number", "nurse", "nut", "object", "objective", "observe", "obtain", "obvious",
    "occasion", "occur", "ocean", "october", "odd", "offer", "office", "officer", "official", "often",
    "oil", "okay", "old", "olive", "olympic", "once", "one", "ongoing", "onion", "online",
    "only", "onto", "open", "operate", "opinion", "oppose", "option", "orange", "order", "ordinary",
    "organ", "organic", "organize", "origin", "original", "other", "ought", "outcome", "outdoor", "outer",
    "output", "outside", "overall", "overcome", "overlap", "overseas", "own", "owner", "pace", "pack",
    "package", "page", "pain", "paint", "painting", "pair", "palace", "palm", "pan", "panel",
    "panic", "paper", "parent", "park", "parking", "part", "particle", "particular", "partly", "partner",
    "party", "pass", "passage", "passenger", "passion", "past", "patch", "path", "patient", "patrol",
    "pattern", "pause", "payment", "peace", "peak", "pen", "penalty", "people", "pepper", "percent",
    "perfect", "perform", "perhaps", "period", "permit", "person", "personal", "persuade", "phase", "phone",
    "photo", "phrase", "physical", "piano", "pick", "picture", "piece", "pile", "pill", "pilot",
    "pink", "pipe", "pitch", "pizza", "place", "plan", "plane", "planet", "plant", "plastic",
    "plate", "platform", "play", "player", "please", "pleasure", "plenty", "plot", "plus", "pocket",
    "poem", "poet", "poetry", "point", "pole", "police", "policy", "politics", "poll", "pool",
    "poor", "popular", "population", "port", "portion", "portrait", "position", "positive", "possess", "possible",
    "post", "potato", "potential", "pound", "pour", "poverty", "powder", "power", "powerful", "practice",
    "pray", "prayer", "precise", "predict", "prefer", "pregnant", "premium", "prepare", "present", "preserve",
    "press", "pressure", "pretend", "pretty", "prevent", "previous", "price", "pride", "primary", "prime",
    "prince", "princess", "print", "prior", "priority", "prison", "prisoner", "privacy", "private", "probably",
    "problem", "process", "produce", "product", "profit", "program", "project", "promise", "promote", "prompt",
    "proof", "proper", "property", "proposal", "propose", "protect", "proud", "prove", "provide", "public",
    "publish", "pull", "purpose", "push", "put", "qualify", "quality", "quarter", "queen", "question",
    "quick", "quiet", "quit", "quite", "quote", "race", "racial", "radio", "rail", "rain",
    "raise", "range", "rank", "rapid", "rare", "rate", "rather", "rating", "ratio", "raw",
    "reach", "react", "read", "reading", "ready", "real", "reality", "realize", "really", "reason",
    "rebel", "recall", "receive", "recent", "recipe", "record", "recover", "red", "reduce", "refer",
    "reflect", "reform", "refuse", "regard", "region", "regular", "reject", "relate", "relation", "relative",
    "relax", "release", "relevant", "reliable", "relief", "religion", "rely", "remain", "remember", "remind",
    "remote", "remove", "repeat", "replace", "reply", "report", "represent", "reputation", "request", "require",
    "rescue", "research", "resemble", "reserve", "resident", "resist", "resolve", "resource", "respect", "respond",
    "response", "rest", "restore", "restrict", "result", "retail", "retain", "retire", "return", "reveal",
    "revenue", "review", "revolution", "reward", "rhythm", "rich", "ride", "ridge", "right", "ring",
    "rise", "risk", "ritual", "rival", "river", "road", "rob", "robot", "rock", "role",
    "roll", "romantic", "roof", "room", "root", "rope", "rose", "rotate", "rough", "round",
    "route", "routine", "row", "royal", "rub", "rubber", "rude", "rule", "run", "rural",
    "rush", "sad", "safe", "safety", "sail", "saint", "sake", "salad", "salary", "sale",
    "salt", "same", "sample", "sand", "satellite", "satisfy", "sauce", "save", "saving", "say",
    "scale", "scandal", "scared", "scenario", "scene", "schedule", "scheme", "scholar", "school", "science",
    "scope", "score", "scratch", "screen", "script", "sea", "search", "season", "seat", "second",
    "secret", "section", "sector", "secure", "security", "see", "seed", "seek", "seem", "select",
    "self", "sell", "senate", "senator", "send", "senior", "sense", "sentence", "separate", "sequence",
    "series", "serious", "serve", "service", "session", "set", "setting", "settle", "setup", "seven",
    "several", "severe", "sex", "shade", "shadow", "shake", "shall", "shame", "shape", "share",
    "sharp", "she", "sheet", "shelf", "shell", "shelter", "shift", "shine", "ship", "shirt",
    "shock", "shoe", "shoot", "shop", "short", "shot", "should", "shoulder", "shout", "show",
    "shower", "sick", "side", "sight", "sign", "signal", "silence", "silent", "silly", "silver",
    "similar", "simple", "simply", "since", "sing", "singer", "single", "sink", "sir", "sister",
    "sit", "site", "situation", "six", "size", "skill", "skin", "sky", "slave", "sleep",
    "slice", "slide", "slight", "slip", "slow", "small", "smart", "smell", "smile", "smoke",
    "smooth", "snap", "snow", "so", "soap", "soccer", "social", "society", "sock", "soft",
    "software", "soil", "solar", "sold", "sole", "solid", "solution", "solve", "some", "somebody",
    "somehow", "someone", "something", "sometimes", "somewhat", "somewhere", "son", "song", "soon", "sophisticated",
    "sort", "soul", "sound", "soup", "source", "south", "southern", "space", "spare", "speak",
    "special", "species", "specific", "speech", "speed", "spell", "spend", "spent", "spin", "spirit",
    "spiritual", "split", "sponsor", "sport", "spot", "spread", "spring", "square", "squeeze", "stable",
    "staff", "stage", "stain", "stair", "stake", "stand", "standard", "star", "stare", "start",
    "state", "statement", "station", "status", "stay", "steady", "steal", "steel", "step", "stick",
    "still", "stimulus", "sting", "stock", "stomach", "stone", "stop", "storage", "store", "storm",
    "story", "straight", "strain", "strand", "strange", "stranger", "strategy", "stream", "street", "strength",
    "stress", "stretch", "strike", "string", "strip", "stroke", "strong", "structure", "struggle", "stuck",
    "student", "studio", "study", "stuff", "stupid", "style", "subject", "submit", "subsequent", "substance",
    "succeed", "success", "such", "sudden", "suffer", "sufficient", "sugar", "suggest", "suit", "summer",
    "summit", "sun", "super", "supply", "support", "suppose", "sure", "surface", "surgery", "surprise",
    "surround", "survey", "survive", "suspect", "sustain", "swallow", "swamp", "swap", "swear", "sweat",
    "sweep", "sweet", "swim", "swing", "switch", "symbol", "symptom", "system", "table", "tackle",
    "tail", "take", "tale", "talent", "talk", "tall", "tank", "tap", "tape", "target",
    "task", "taste", "tax", "taxi", "tea", "teach", "teacher", "team", "tear", "tech",
    "technique", "technology", "teen", "telephone", "telescope", "television", "tell", "temperature", "temple", "temporary",
    "ten", "tend", "tennis", "tension", "tent", "term", "terminal", "terrible", "territory", "terror",
    "test", "text", "than", "thank", "that", "the", "theater", "their", "them", "theme",
    "themselves", "then", "theory", "therapy", "there", "therefore", "these", "they", "thick", "thin",
    "thing", "think", "third", "this", "thorough", "those", "though", "thought", "thousand", "threat",
    "three", "through", "throw", "thumb", "thus", "ticket", "tide", "tie", "tight", "time",
    "tiny", "tip", "tire", "tissue", "title", "tobacco", "today", "toe", "together", "tomato",
    "tomorrow", "tone", "tongue", "tonight", "too", "tool", "tooth", "top", "topic", "total",
    "touch", "tough", "tour", "tourist", "tournament", "toward", "towards", "town", "toy", "track",
    "trade", "tradition", "traffic", "train", "training", "transfer", "transform", "transport", "trap", "trash",
    "travel", "treat", "treatment", "tree", "tremendous", "trend", "trial", "tribe", "trick", "trip",
    "troop", "trouble", "truck", "true", "truly", "trust", "truth", "try", "tube", "tune",
    "tunnel", "turn", "twelve", "twenty", "twice", "twin", "twist", "two", "type", "typical",
    "ugly", "ultimate", "unable", "uncle", "under", "undergo", "understand", "unemployment", "unfortunately", "uniform",
    "union", "unique", "unit", "unite", "unity", "universe", "university", "unknown", "unless", "unlike",
    "unlikely", "until", "unusual", "up", "upon", "upper", "urban", "urge", "urgent", "us",
    "use", "used", "useful", "user", "usual", "utility", "vacation", "valley", "valuable", "value",
    "variable", "variation", "variety", "various", "vast", "vegetable", "vehicle", "venture", "version", "versus",
    "very", "vessel", "veteran", "via", "victim", "victory", "video", "view", "village", "violate",
    "violence", "violent", "virtual", "virus", "visible", "vision", "visit", "visual", "vital", "voice",
    "volume", "volunteer", "vote", "vulnerable", "wage", "wait", "wake", "walk", "wall", "want",
    "war", "warm", "warn", "wash", "waste", "watch", "water", "wave", "way", "we",
    "weak", "wealth", "weapon", "wear", "weather", "web", "website", "wedding", "week", "weekend",
    "weekly", "weight", "weird", "welcome", "welfare", "well", "west", "western", "what", "whatever",
    "wheel", "when", "whenever", "where", "whereas", "wherever", "whether", "which", "while", "whisper",
    "white", "who", "whole", "whom", "whose", "why", "wide", "wife", "wild", "will",
    "win", "wind", "window", "wine", "wing", "winner", "winter", "wire", "wise", "wish",
    "with", "withdraw", "within", "without", "witness", "woman", "wonder", "wonderful", "wood", "wooden",
    "wool", "word", "work", "worker", "working", "workplace", "world", "worried", "worry", "worse",
    "worst", "worth", "would", "wound", "wrap", "write", "writer", "writing", "wrong", "yard",
    "yeah", "year", "yellow", "yes", "yesterday", "yet", "yield", "you", "young", "your",
    "yourself", "youth", "zone"
];

/// Generate XKCD-style password with 4 words separated by hyphens
pub fn generate_password() -> String {
    let mut rng = thread_rng();
    let words: Vec<&str> = (0..4)
        .map(|_| WORD_LIST[rng.gen_range(0..WORD_LIST.len())])
        .collect();
    words.join("-")
}

/// Hash password using Argon2
pub fn hash_password(password: &str) -> crate::Result<String> {
    use argon2::{Argon2, PasswordHasher, password_hash::{SaltString, rand_core::OsRng}};
    
    let salt = SaltString::generate(&mut OsRng);
    let argon2 = Argon2::default();
    
    match argon2.hash_password(password.as_bytes(), &salt) {
        Ok(hash) => Ok(hash.to_string()),
        Err(e) => Err(crate::StaticLeafError::Auth(format!("Failed to hash password: {}", e))),
    }
}

/// Verify password against hash
pub fn verify_password(password: &str, hash: &str) -> crate::Result<bool> {
    use argon2::{Argon2, PasswordHash, PasswordVerifier};
    
    let parsed_hash = PasswordHash::new(hash)
        .map_err(|e| crate::StaticLeafError::Auth(format!("Invalid password hash: {}", e)))?;
    
    match Argon2::default().verify_password(password.as_bytes(), &parsed_hash) {
        Ok(()) => Ok(true),
        Err(_) => Ok(false),
    }
}